
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Label lonLabel;
	
	private global::Gtk.Entry lonEntry;
	
	private global::Gtk.Label latLabel;
	
	private global::Gtk.Entry latEntry;
	
	private global::Gtk.Button getInfoButton;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label myLonLabel;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Label myLatLabel;
	
	private global::Gtk.Label myIPLabel;
	
	private global::Gtk.Label cityLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lonLabel = new global::Gtk.Label ();
		this.lonLabel.Name = "lonLabel";
		this.lonLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Longitude:");
		this.vbox1.Add (this.lonLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lonLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lonEntry = new global::Gtk.Entry ();
		this.lonEntry.CanFocus = true;
		this.lonEntry.Name = "lonEntry";
		this.lonEntry.IsEditable = true;
		this.lonEntry.InvisibleChar = '●';
		this.vbox1.Add (this.lonEntry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lonEntry]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.latLabel = new global::Gtk.Label ();
		this.latLabel.Name = "latLabel";
		this.latLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Latitude:");
		this.vbox1.Add (this.latLabel);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.latLabel]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.latEntry = new global::Gtk.Entry ();
		this.latEntry.CanFocus = true;
		this.latEntry.Name = "latEntry";
		this.latEntry.IsEditable = true;
		this.latEntry.InvisibleChar = '●';
		this.vbox1.Add (this.latEntry);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.latEntry]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.getInfoButton = new global::Gtk.Button ();
		this.getInfoButton.CanFocus = true;
		this.getInfoButton.Name = "getInfoButton";
		this.getInfoButton.UseUnderline = true;
		this.getInfoButton.Label = global::Mono.Unix.Catalog.GetString ("Get info about this location");
		this.vbox1.Add (this.getInfoButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.getInfoButton]));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.myLonLabel = new global::Gtk.Label ();
		this.myLonLabel.Name = "myLonLabel";
		this.myLonLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Moja dł. geo.");
		this.vbox2.Add (this.myLonLabel);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.myLonLabel]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.myLatLabel = new global::Gtk.Label ();
		this.myLatLabel.Name = "myLatLabel";
		this.myLatLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Moja szer. geo.");
		this.vbox3.Add (this.myLatLabel);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.myLatLabel]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.myIPLabel = new global::Gtk.Label ();
		this.myIPLabel.Name = "myIPLabel";
		this.myIPLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Moje IP");
		this.vbox3.Add (this.myIPLabel);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.myIPLabel]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
		w10.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.cityLabel = new global::Gtk.Label ();
		this.cityLabel.Name = "cityLabel";
		this.cityLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Tu bedzie miasto z tej lokalizacji");
		this.vbox2.Add (this.cityLabel);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.cityLabel]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 401;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.getInfoButton.Clicked += new global::System.EventHandler (this.getInfoButton_clicked);
	}
}
